### PR TITLE
Added Dummy Data to Start With

### PR DESCRIPTION
**Pull request by MissPeperr**
Added insert statements in `bangazon.sql`
There should be 3 rows in each Table

### CODE REVIEW

**Review by MarkHale94 — CHANGES_REQUESTED** [review]
organize plz

**Review by MarkHale94 — APPROVED** [review]
I guess it's ok

**Review by edwards-j — APPROVED** [review]
If the Gitstapo says its ok, it's ok

**Review by davidnicholastaylor — APPROVED** [review]
Fantastic. Really glad the insert statements are on their own and don't follow their specific tables.

**Pull request merged**
